# Parse all files with TypeScript.
extends:
  - 'standard-with-typescript'
  - 'prettier'

parserOptions:
  project: './tsconfig.json'
  createDefaultProgram: true

plugins:
  - prettier
  - react
  - jest
  - jest-dom
  - '@typescript-eslint'
  - react-hooks

settings:
  react:
    version: detect

env:
  browser: true

rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: error

  '@typescript-eslint/no-unnecessary-type-assertion': off
  '@typescript-eslint/consistent-type-definitions': off
  '@typescript-eslint/no-empty-interface': off
  '@typescript-esclint/strict-boolean-expressions': off

  no-unused-vars: off
  '@typescript-eslint/no-unused-vars':
    - error
    - varsIgnorePattern: _
      argsIgnorePattern: _

  no-void: off
